#DEV Environment

##Versao .properties
#app.message = This is the property file to the ${spring.application.name} It's a test - Oh Yeah
#
#spring.datasource.driver-class-name = org.h2.Driver
#spring.datasource.url = jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#spring.datasource.username = sa
#spring.datasource.password = sa

##Versao .yml
app:
  message: This is the property file to the ${spring.application.name} Oh Yeah

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa