--CREATE TABLE PRODUTOS(
--	CODIGO			INT				NOT NULL,
--	DESCRICAO		VARCHAR(50)		NOT NULL,
--	DATA_VALIDADE	DATETIME,
--	EAN				VARCHAR(15)		NOT NULL,
--	IND_INATIVO		INT				NOT NULL DEFAULT 0,
--)

--ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (CODIGO)

--CLASSIFICAR O CAMPO EAN COMO UM INDEX
--CREATE INDEX IDX_PRODUTOS_EAN ON PRODUTOS(EAN)

--INSERT INTO PRODUTOS VALUES(1, 'Nome do produto', GETDATE(), '1234567890', 0)
--INSERT INTO PRODUTOS (CODIGO, DESCRICAO, EAN) VALUES(2, 'Nome dE OUTRO produto', '1234567890')

--TIPOS DE SELECT
SELECT *
FROM PRODUTOS
WHERE
	--CODIGO = 2
	DESCRICAO LIKE '%PROD%'

--AGREGACAO
SELECT COUNT(*)
FROM PRODUTOS TOTAL

--CREATE TABLE LOJAS(
--	CODIGO			INT				NOT NULL,
--	NOME			VARCHAR(50)		NOT NULL,
--	IND_INATIVO		INT				NOT NULL	DEFAULT 0,
--	CONSTRAINT		PK_LOJA			PRIMARY KEY (CODIGO),
--)

--INSERT INTO LOJAS (CODIGO, NOME) VALUES (1000, 'Filial Nova Iguaçu'), (2000, 'Filial São Paulo'), (3000, 'Filial Recife')

SELECT * FROM LOJAS

--CREATE TABLE ESTOQUE(
--	CODIGO_PRODUTO			INT			NOT NULL,
--	CODIGO_FILIAL			INT			NOT NULL,
--	QUANTIDADE				DECIMAL		NOT NULL DEFAULT 0,
--	CONSTRAINT				PK_ESTOQUE	PRIMARY KEY (CODIGO_PRODUTO, CODIGO_FILIAL),

--)

--ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_PRODUTOS FOREIGN KEY (CODIGO_PRODUTO) REFERENCES PRODUTOS (CODIGO)
--ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_LOJAS FOREIGN KEY (CODIGO_FILIAL) REFERENCES LOJAS (CODIGO)

--INSERT INTO ESTOQUE (CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (1, 1000, 1)

SELECT
	E.CODIGO_FILIAL,
	L.NOME,
	E.CODIGO_PRODUTO,
	P.DESCRICAO,
	E.QUANTIDADE
FROM ESTOQUE E
INNER JOIN LOJAS L ON E.CODIGO_FILIAL = L.CODIGO
INNER JOIN PRODUTOS P ON P.CODIGO = E.CODIGO_PRODUTO


---OUTROS COMANDOS
--ALTER TABLE DROP CONSTRAINT NOME_CONSTRAINT
--DROP TABLE NOME_TABELA
--DROP INDEX NOME_INDEX

