USE Ecommerce

SELECT *
FROM DBO.CLIENTES
--WHERE CODIGO = 1 OR TIPO_PESSOA = 'J'
SELECT * FROM PRODUTOS
SELECT * FROM PEDIDO
SELECT * FROM PEDIDO_ITEM

--INSERT INTO CLIENTES (CODIGO, NOME, TIPO_PESSOA) VALUES (1, 'Thiago', 'F')
--INSERT CLIENTES (CODIGO, NOME, TIPO_PESSOA) VALUES (2, 'Matheus', 'F')
--INSERT CLIENTES VALUES (3, 'Carlos', 'F'), (4, 'Bruno', 'F'), (5, 'Marly', 'F'), (1, 'Stan', 'J')

--UPDATE CLIENTES SET CODIGO = 6 WHERE CODIGO = 1 AND TIPO_PESSOA = 'J'
--DELETE FROM CLIENTES WHERE CODIGO IN (5, 4, 3, 2)

--INSERT INTO PRODUTOS VALUES (1, 'CANETA', 'CANETA AZUL', 1.5), (2, 'CADERNO', 'CADERNO 10 MATERIAS', 20.95)

--INSERT INTO PEDIDO VALUES(1, GETDATE(), 0, 3, 6)
--INSERT INTO PEDIDO VALUES(2, GETDATE(), 0, 23.95, 1)

--INSERT INTO PEDIDO_ITEM VALUES(1, 1, 1.5, 2)
--INSERT INTO PEDIDO_ITEM VALUES(2, 2, 22.49, 1), (2, 1, 1.5, 1)

--SELECT *,
--	CONVERT(VARCHAR, DATA_SOLICITACAO, 103)
--FROM PEDIDO

--SELECT *,
--	CASE
--		WHEN TIPO_PESSOA = 'F' THEN 'FISICA'
--		WHEN TIPO_PESSOA = 'J' THEN 'JURIDICA'
--		ELSE 'PESSOA INDEFINIDA' 
--	END + ' ' + CONVERT(VARCHAR, GETDATE(), 103)
--FROM CLIENTES

