CREATE TABLE PILOTOS_NAVES(
	ID_PILOTO INT NOT NULL,
	ID_NAVE INT NOT NULL,
	FLAG_AUTORIZADO BIT NOT NULL,
)
GO
ALTER TABLE PILOTOS_NAVES ADD CONSTRAINT PK_PILOTOS_NAVES PRIMARY KEY (ID_PILOTO, ID_NAVE);
GO
ALTER TABLE PILOTOS_NAVES ADD CONSTRAINT FK_PILOTOS_NAVES_PILOTOS FOREIGN KEY (ID_PILOTO) REFERENCES PILOTOS (ID_PILOTO);
GO
ALTER TABLE PILOTOS_NAVES ADD CONSTRAINT FK_PILOTOS_NAVES_NAVES FOREIGN KEY (ID_NAVE) REFERENCES NAVES (ID_NAVE);
GO
ALTER TABLE PILOTOS_NAVES ADD CONSTRAINT DF_PILOTO_NAVES_FLAG_AUTORIZADO DEFAULT (1) FOR FLAG_AUTORIZADO --SE NÃO FOR INDICADO NENHUM VALOR, POR PADRAO, ESTE VALOR SERÁ 1



CREATE TABLE HISTORICO_VIAGENS(
	ID_NAVE INT NOT NULL,
	ID_PILOTO INT NOT NULL,
	DATA_SAIDA DATETIME NOT NULL,
	DATA_CHEGADA DATETIME NOT NULL,
)
GO
ALTER TABLE HISTORICO_VIAGENS ADD CONSTRAINT FK_HISTORICO_VIAGENS_PILOTOS_NAVES FOREIGN KEY (ID_PILOTO, ID_NAVE) REFERENCES PILOTOS_NAVES (ID_PILOTO, ID_NAVE)
GO
ALTER TABLE HISTORICO_VIAGENS CHECK CONSTRAINT FK_HISTORICO_VIAGENS_PILOTOS_NAVES