CREATE TABLE PLANETAS(
	ID_PLANETA INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	ROTACAO FLOAT NOT NULL,
	ORBITA FLOAT NOT NULL,
	DIAMETRO FLOAT NOT NULL,
	CLIMA VARCHAR(50) NOT NULL,
	POPULACAO INT NOT NULL,
)
GO
ALTER TABLE PLANETAS ADD CONSTRAINT PK_PLANETAS PRIMARY KEY (ID_PLANETA);


